BeserShop/BeserShop/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace BeserShop.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BeserShop/BeserShop/Controllers/CustomerController.cs
using BeserShop.Data;
using BeserShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace BeserShop.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CustomerController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var List = _db.Customers.ToList(); //sql deki tablo ismimiz derneks olduğu için yazdık.
            return View(List);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Customer customer)
        {
            _db.Add(customer);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int? id) // ? işareti koyma nedenimiz null geçilebilir demek.
        {
            var update = _db.Customers.Find(id);
            return View(update);
        }
        [HttpPost]
        public IActionResult Edit(int? id, Customer customer)
        {
            _db.Update(customer);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var delete = _db.Customers.FirstOrDefault(m => m.CustomerID == id);
            return View(delete);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult Sil(int id)
        {
            var delete = _db.Customers.FirstOrDefault(m => m.CustomerID == id);
            _db.Customers.Remove(delete);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BeserShop/BeserShop/Controllers/MeatProductController.cs
using BeserShop.Data;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace BeserShop.Controllers
{
    public class MeatProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        public MeatProductController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var List = _db.MeatProducts.ToList();
            return View(List);
        }
    }
}

BeserShop/BeserShop/Controllers/SupplierController.cs
using BeserShop.Data;
using BeserShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace BeserShop.Controllers
{
    public class SupplierController : Controller
    {
        private readonly ApplicationDbContext _db;
        public SupplierController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var List = _db.Suppliers.ToList(); //sql deki tablo ismimiz derneks olduğu için yazdık.
            return View(List);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Supplier supplier)
        {
            _db.Add(supplier);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int? id) // ? işareti koyma nedenimiz null geçilebilir demek.
        {
            var update = _db.Suppliers.Find(id);
            return View(update);
        }
        [HttpPost]
        public IActionResult Edit(int? id, Supplier supplier)
        {
            _db.Update(supplier);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var delete = _db.Suppliers.FirstOrDefault(m => m.SupplierID == id);
            return View(delete);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult Sil(int id)
        {
            var delete = _db.Suppliers.FirstOrDefault(m => m.SupplierID == id);
            _db.Suppliers.Remove(delete);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BeserShop/BeserShop/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/adminTemp/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/adminTemp/assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>BeserShop</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="~/adminTemp/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/adminTemp/assets/css/light-bootstrap-dashboard.css?v=2.0.0 " rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="~/adminTemp/assets/css/demo.css" rel="stylesheet" />
</head>

<body>
    <div class="wrapper">
        <div class="sidebar" data-color="red">
            @*<div class="sidebar" data-image="~/adminTemp/assets/img/sidebar-5.jpg">*@
            <!--
                Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

                Tip 2: you can also add an image using data-image tag
            -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="http://www.creative-tim.com" class="simple-text">
                        Creative Tim
                    </a>
                </div>
                <ul class="nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index","Admin")">
                            <i class="nc-icon nc-chart-pie-35"></i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","Customer")">
                            <i class="nc-icon nc-circle-09"></i>
                            <p>Customers</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","Supplier")">
                            <i class="nc-icon nc-notes"></i>
                            <p>Suppliers</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","AMeatProduct")">
                            <i class="nc-icon nc-paper-2"></i>
                            <p>Meat Products</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","AVeganProduct")">
                            <i class="nc-icon nc-atom"></i>
                            <p>Vegan Products</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","AVegetarianProductHome")">
                            <i class="nc-icon nc-pin-3"></i>
                            <p>Vegetarian Products</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg " color-on-scroll="500">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#pablo"> Dashboard </a>
                    <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index","Home")">
                                    <span class="no-icon">Log out</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav>
                        <ul class="footer-menu">
                            <li>
                                <a href="#">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Company
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Portfolio
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Blog
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-center">
                            ©
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                        </p>
                    </nav>
                </div>
            </footer>
        </div>
    </div>
</body>
<!--   Core JS Files   -->
<script src="~/adminTemp/assets/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="~/adminTemp/assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="~/adminTemp/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="~/adminTemp/assets/js/plugins/bootstrap-switch.js"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!--  Chartist Plugin  -->
<script src="~/adminTemp/assets/js/plugins/chartist.min.js"></script>
<!--  Notifications Plugin    -->
<script src="~/adminTemp/assets/js/plugins/bootstrap-notify.js"></script>
<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
<script src="~/adminTemp/assets/js/light-bootstrap-dashboard.js?v=2.0.0 " type="text/javascript"></script>
<!-- Light Bootstrap Dashboard DEMO methods, don't include it in your project! -->
<script src="~/adminTemp/assets/js/demo.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        // Javascript method's body can be found in assets/js/demos.js
        demo.initDashboardPageCharts();

        demo.showNotification();

    });
</script>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</html>

BeserShop/BeserShop/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>BeserShop</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/hometemp/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/hometemp/css/animate.css">
    <link rel="stylesheet" href="~/hometemp/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/hometemp/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/hometemp/css/magnific-popup.css">

    <link rel="stylesheet" href="~/hometemp/css/aos.css">

    <link rel="stylesheet" href="~/hometemp/css/ionicons.min.css">

    <link rel="stylesheet" href="~/hometemp/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/hometemp/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/hometemp/css/flaticon.css">
    <link rel="stylesheet" href="~/hometemp/css/icomoon.css">
    <link rel="stylesheet" href="~/hometemp/css/style.css">
</head>
<body class="goto-here">
    <div class="py-1 bg-primary">
        <div class="container">
            <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
                <div class="col-lg-12 d-block">
                    <div class="row d-flex">
                        <div class="col-md pr-4 d-flex topper align-items-center">
                            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
                            <span class="text">+90 546 048 2565</span>
                        </div>
                        <div class="col-md pr-4 d-flex topper align-items-center">
                            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
                            <span class="text">info@besershop.com</span>
                        </div>
                        <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
                            <span class="text">3-5 Business days delivery &amp; Free Returns</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index","Home")">Beşer Shop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> Menu
            </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a href="@Url.Action("Index","Home")" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","VegetarianProduct")" class="nav-link">Vegetarian Foods</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","VeganProduct")" class="nav-link">Vegan Foods</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","MeatProduct")" class="nav-link">Meat Foods</a></li>
                    <li class="nav-item"><a href="@Url.Action("About","Home")" class="nav-link">About</a></li>
                    <li class="nav-item"><a href="@Url.Action("Contact","Home")" class="nav-link">Contact</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","Admin")" class="nav-link">Admin</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- END nav -->
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    <div class="row mb-5">
        <div class="col-md-6">
            <div class="ftco-footer-widget mb-4 ml-md-5">
                <h2 class="ftco-heading-2">Menu</h2>
                <ul class="list-unstyled">
                    <li class="nav-item active"><a href="@Url.Action("Index","Home")" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","VegetarianProduct")" class="nav-link">Vegetarian Foods</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","VeganProduct")" class="nav-link">Vegan Foods</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","MeatProduct")" class="nav-link">Meat Foods</a></li>
                    <li class="nav-item"><a href="@Url.Action("About","Home")" class="nav-link">About</a></li>
                    <li class="nav-item"><a href="@Url.Action("Contact","Home")" class="nav-link">Contact</a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-6">
            <div class="ftco-footer-widget mb-4">
                <h2 class="ftco-heading-2">Have a Questions?</h2>
                <div class="block-23 mb-3">
                    <ul>
                        <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, Esenyurt, İstanbul, Türkiye</span></li>
                        <li><a href="#"><span class="icon icon-phone"></span><span class="text">+90 546 048 2565</span></a></li>
                        <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@besershop.com</span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-center">

            <p>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
    </div>

    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>


    <script src="~/hometemp/js/jquery.min.js"></script>
    <script src="~/hometemp/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/hometemp/js/popper.min.js"></script>
    <script src="~/hometemp/js/bootstrap.min.js"></script>
    <script src="~/hometemp/js/jquery.easing.1.3.js"></script>
    <script src="~/hometemp/js/jquery.waypoints.min.js"></script>
    <script src="~/hometemp/js/jquery.stellar.min.js"></script>
    <script src="~/hometemp/js/owl.carousel.min.js"></script>
    <script src="~/hometemp/js/jquery.magnific-popup.min.js"></script>
    <script src="~/hometemp/js/aos.js"></script>
    <script src="~/hometemp/js/jquery.animateNumber.min.js"></script>
    <script src="~/hometemp/js/bootstrap-datepicker.js"></script>
    <script src="~/hometemp/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/hometemp/js/google-map.js"></script>
    <script src="~/hometemp/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BeserShop/BeserShop/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeserShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeserShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BeserShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>